export const translations = {
  fr: {
    title: "Hétéro ou Homo ?",
    subtitle: "L'intelligence artificielle a la réponse (absurde)",
    placeholder: "Une chose, un concept, un aliment…",
    go: "GO",
    loading: "L'IA réfléchit intensément…",
    agree: "D'accord",
    disagree: "Pas d'accord",
    share: "Partager",
    copied: "Copié !",
    disclaimer: "Réponses générées par une intelligence artificielle. À prendre avec humour et au second degré.",
    verdicts: {
      Hétérosexuelle: "Hétérosexuelle",
      Homosexuelle: "Homosexuelle",
      "Aucun des deux": "Aucun des deux"
    }
  },
  en: {
    title: "Straight or Gay?",
    subtitle: "Artificial intelligence has the (absurd) answer",
    placeholder: "A thing, a concept, a food…",
    go: "GO",
    loading: "The AI is thinking hard…",
    agree: "Agree",
    disagree: "Disagree",
    share: "Share",
    copied: "Copied!",
    disclaimer: "Responses generated by an AI. To be taken with humor and a grain of salt.",
    verdicts: {
      Hétérosexuelle: "Straight",
      Homosexuelle: "Gay",
      "Aucun des deux": "Neither"
    }
  },
  es: {
    title: "¿Hetero o Homo?",
    subtitle: "La inteligencia artificial tiene la respuesta (absurda)",
    placeholder: "Una cosa, un concepto, una comida…",
    go: "IR",
    loading: "La IA está pensando profundamente…",
    agree: "De acuerdo",
    disagree: "En desacuerdo",
    share: "Compartir",
    copied: "¡Copiado!",
    disclaimer: "Respuestas generadas por una inteligencia artificial. Tómatelo con humor y de forma no literal.",
    verdicts: {
      Hétérosexuelle: "Heterosexual",
      Homosexuelle: "Homosexual",
      "Aucun des deux": "Ninguno"
    }
  }
};

export type Lang = keyof typeof translations;
